name: Run Zippy

env:
  DEFAULT_OUTPUT_PATH: './sampleLogs'
  DEFAULT_DATE: '2026-05-02'
  DEFAULT_TIME: '11-15-00'

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      output_path:
        description: '출력 폴더 경로'
        required: true
        type: string
      date:
        description: '날짜 (YYYY-MM-DD)'
        required: true
        type: string
      time:
        description: '시간 (HH-MM-SS)'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python setting
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'

      - name: Run script
        run: |
          python main_ci.py \
            --output_path "${{ github.event.inputs.output_path || env.DEFAULT_OUTPUT_PATH }}" \
            --date "${{ github.event.inputs.date || env.DEFAULT_DATE }}" \
            --time "${{ github.event.inputs.time || env.DEFAULT_TIME }}"